packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/generators/app.js, packages/rax-miniapp-runtime-webpack-plugin/src/templates/rax-default.css.ejs
=> feat(miniapp): add __rax-view and __rax-text in default css

packages/miniapp-builder-shared/package.json, packages/miniapp-builder-shared/src/filterNativePages.js, packages/miniapp-compile-config/package.json, packages/miniapp-compile-config/src/setAppConfig.js, packages/miniapp-compile-config/src/setBaseConfig.js, packages/miniapp-compile-config/src/setComponentConfig.js, packages/rax-miniapp-config-webpack-plugin/package.json, packages/rax-miniapp-config-webpack-plugin/src/handleIcon.js
=> fix: some bug in miniapp

packages/miniapp-render/package.json, packages/miniapp-render/src/constants.js, packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/templates/ali-miniapp/root.xml.ejs
support for lottie
https://opendocs.alipay.com/mini/component/lottie
=> feat: support lottie

packages/jsx-compiler/package.json, packages/jsx-compiler/src/modules/code.js, packages/jsx-compiler/src/modules/config.js, packages/jsx2mp-loader/package.json, packages/jsx2mp-loader/src/app-loader.js, packages/jsx2mp-loader/src/component-loader.js, packages/jsx2mp-loader/src/output.js, packages/jsx2mp-loader/src/page-loader.js, packages/jsx2mp-loader/src/script-loader.js, packages/jsx2mp-runtime/package.json, packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/component.js, packages/jsx2mp-runtime/src/createRef.js, packages/jsx2mp-runtime/src/cycles.js, packages/jsx2mp-runtime/src/history.js, packages/jsx2mp-runtime/src/index.js, packages/jsx2mp-runtime/src/page.js, packages/jsx2mp-runtime/src/version.js, packages/miniapp-compile-config/package.json, packages/miniapp-compile-config/src/plugins/ModifyOutputFileSystem.js, packages/miniapp-compile-config/src/plugins/RemoveDefaultResult.js, packages/miniapp-compile-config/src/setAppConfig.js, packages/miniapp-compile-config/src/setBaseConfig.js, packages/miniapp-compile-config/src/setComponentConfig.js
=> feat: miniapp compile adapt rax-app

packages/miniapp-render/src/bridge/createEventProxy.js, packages/miniapp-render/src/bridge/injectLifeCycle.js, packages/miniapp-render/src/builtInComponents/button.js, packages/miniapp-render/src/createConfig/page.js, packages/miniapp-render/src/document.js, packages/miniapp-render/src/event/event-target.js, packages/miniapp-render/src/node/element.js, packages/miniapp-render/src/node/element/input.js, packages/miniapp-render/src/node/element/textarea.js, packages/miniapp-render/src/node/node.js, packages/miniapp-render/src/node/root.js, packages/miniapp-render/src/utils/cache.js, packages/miniapp-render/src/utils/tree.js, packages/miniapp-render/src/window.js, packages/rax-miniapp-runtime-webpack-plugin/src/templates/ali-miniapp/root.xml.ejs, packages/rax-miniapp-runtime-webpack-plugin/src/templates/ali-miniapp/tool.sjs.ejs, packages/rax-miniapp-runtime-webpack-plugin/src/templates/wechat-miniprogram/root.xml.ejs, packages/rax-miniapp-runtime-webpack-plugin/src/templates/wechat-miniprogram/tool.wxs.ejs
Pay Attention: 
- 事件系统将不再根据 pageId 做隔离，此举导致挂载在 window 上的 page 事件可能互相影响，需要更改为在 document 上注册和触发事件
- appendChild 等场景下，父子节点出现 ownerDocument 不一致的情况时，需要从对子节点整棵树进行遍历修正
=> fix(miniapp): async update

packages/miniapp-builder-shared/package.json, packages/miniapp-builder-shared/src/pathHelper.js, packages/miniapp-compile-config/README.md, packages/rax-miniapp-babel-plugins/package.json, packages/rax-miniapp-babel-plugins/src/constants.js, packages/rax-miniapp-babel-plugins/src/plugins/babel-plugin-handle-native-component.js, packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/generators/render.js, packages/rax-miniapp-runtime-webpack-plugin/src/index.js
新增能力说明见 https://github.com/raxjs/miniapp/issues/32
=> feat(miniapp): support compiled components in runtime project

packages/jsx-compiler/package.json, packages/jsx-compiler/src/utils/pathHelper.js, packages/jsx2mp-loader/package.json, packages/jsx2mp-loader/src/script-loader.js
=> fix(jsx2mp): missing handle json file

packages/jsx2mp-runtime/package.json, packages/jsx2mp-runtime/src/bridge.js
=> fix(jsx2mp): wrong dataset order bug

packages/jsx-compiler/package.json, packages/jsx-compiler/src/adapter.js, packages/jsx-compiler/src/utils/checkAttr.js, packages/jsx2mp-loader/package.json, packages/jsx2mp-loader/src/script-loader.js, packages/jsx2mp-runtime/package.json
=> release: miniapp [20201230]

packages/miniapp-runtime-config/package.json, packages/miniapp-runtime-config/src/setConfig.js, packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/generators/app.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/element.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/page.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/pkg.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/root.js, packages/rax-miniapp-runtime-webpack-plugin/src/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/utils/getFinalRouteMap.js, packages/rax-miniapp-runtime-webpack-plugin/src/utils/wrapChunks.js
小程序插件生成页面 key 值的时候，要考虑状态管理修改了页面源地址为临时路径 https://github.com/raxjs/rax-app/issues/581
=> fix: miniapp store

packages/jsx2mp-runtime/src/nativeEventListener.js, packages/miniapp-render/src/createConfig/page.js
=> fix(miniapp): update page options in onShow

packages/miniapp-render/renderMock.js, packages/miniapp-render/src/bridge/events/baseEvents.js, packages/miniapp-render/src/createConfig/app.js, packages/miniapp-render/src/createConfig/page.js, packages/miniapp-render/src/utils/cache.js, packages/miniapp-render/src/window.js
=> fix(miniapp): miniapp-render bug

packages/jsx2mp-loader/CHANGELOG.md, packages/jsx2mp-loader/package.json, packages/jsx2mp-loader/src/script-loader.js
- 编译时方案中，对第三方小程序组件，其需要修改的 JSON 文件仅限定自身，否则存在遗漏 JSON 文件的问题
=> fix(jsx2mp): lose json file

packages/rax-miniapp-runtime-webpack-plugin/CHANGELOG.md, packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/generators/page.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/templates/unrecursiveTemplate.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/wechat.js, packages/rax-miniapp-runtime-webpack-plugin/src/utils/isNpmModule.js
=> fix(miniapp): runtime template

packages/miniapp-render/CHANGELOG.md, packages/miniapp-render/package.json, packages/miniapp-render/src/builtInComponents/web-view.js, packages/rax-miniapp-runtime-webpack-plugin/CHANGELOG.md, packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/generators/templates/baseTemplate.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/ali.js
=> fix(miniapp): template update

packages/miniapp-render/src/createConfig/app.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/app.js
支持微信小程序分包 `src/miniapp-native/common` 目录下的 JS 文件共享运行时内存
=> feat: support share memory with subpackages

packages/miniapp-render/src/builtInComponents/index.js, packages/miniapp-render/src/createConfig/app.js, packages/miniapp-runtime-config/src/setConfig.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/ali.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/wechat.js
=> fix(miniapp): runtime bug

packages/miniapp-render/src/constants.js, packages/miniapp-render/src/node/attribute.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/ali.js
- fix: miss contact-button identify
- fix: update dataset should trigger render
- feat: add data-params for ali miniapp
=> fix(miniapp: runtime bug

packages/miniapp-render/src/createConfig/app.js
https://github.com/raxjs/rax-app/pull/677
=> fix: subPackages error with miniapp

packages/jsx-compiler/src/modules/code.js, packages/jsx2mp-loader/src/component-loader.js, packages/jsx2mp-runtime/src/adapter/getComponentBaseConfig.js, packages/jsx2mp-runtime/src/bridge.js, packages/jsx2mp-runtime/src/component.js, packages/miniapp-compile-config/src/setBaseConfig.js
=> feat(jsx2mp): support config virtualHost && fix render props in wecha

packages/miniapp-render/CHANGELOG.md, packages/miniapp-render/package.json, packages/miniapp-render/src/node/attribute.js, packages/miniapp-render/src/utils/tool.js, packages/rax-miniapp-runtime-webpack-plugin/CHANGELOG.md, packages/rax-miniapp-runtime-webpack-plugin/package.json
=> Release/miniapp 0408 

packages/miniapp-render/CHANGELOG.md, packages/miniapp-render/package.json, packages/miniapp-render/src/builtInComponents/textarea.js, packages/miniapp-render/src/node/attribute.js, packages/miniapp-render/src/node/class-list.js, packages/miniapp-render/src/node/element.js, packages/miniapp-render/src/node/node.js, packages/miniapp-render/src/node/root.js, packages/miniapp-render/src/node/style.js, packages/miniapp-render/src/node/text-node.js, packages/rax-miniapp-runtime-webpack-plugin/src/static/default.css, packages/rax-miniapp-runtime-webpack-plugin/src/webTagList.js
=> fix(miniapp): remove unnecessary setData && bug fix

packages/rax-miniapp-runtime-webpack-plugin/src/platforms/ali.js
=> feat: support camera

packages/miniapp-builder-shared/src/constants.js, packages/miniapp-builder-shared/src/platformMap.js, packages/rax-miniapp-babel-plugins/src/constants.js, packages/rax-miniapp-babel-plugins/src/plugins/babel-plugin-handle-native-component.js, packages/rax-miniapp-config-webpack-plugin/src/constants.js, packages/rax-miniapp-config-webpack-plugin/src/transformNativeConfig.js
=> feat: multiple miniapp support config

packages/rax-miniapp-runtime-webpack-plugin/src/generators/templates/baseTemplate.js, packages/rax-miniapp-runtime-webpack-plugin/src/generators/templates/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/ali.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/baidu.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/bytedance.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/kuaishou.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/wechat.js
对于不支持 sjs 的小程序（如字节飞书小程序），去除模板中的函数，全部改用基本的  js 表达式
=> feat(miniapp): support lark miniapp which doesn't support sjs

packages/miniapp-render/src/builtInComponents/camera.js, packages/miniapp-render/src/builtInComponents/picker.js, packages/miniapp-render/src/builtInComponents/swiper.js, packages/miniapp-render/src/builtInComponents/textarea.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/bytedance.js
=> fix(miniapp): template error in bytedance

packages/jsx2mp-runtime/src/bridge.js
=> fix: add app props

packages/rax-miniapp-runtime-webpack-plugin/src/platforms/baidu.js
=> fix(miniapp): template error in baidu

packages/miniapp-render/src/node/style.js
=> feat(miniapp): support css variables

packages/miniapp-render/scripts/platform-plugin.js, packages/miniapp-render/src/constants.js, packages/miniapp-render/src/node/element.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/baidu.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/kuaishou.js
=> feat(miniapp): support flex in baidu and kuaishou

packages/miniapp-render/src/createConfig/page.js, packages/miniapp-render/src/node/element.js, packages/miniapp-render/src/node/element/custom-component.js, packages/miniapp-render/src/node/element/image.js, packages/miniapp-render/src/node/element/input.js, packages/miniapp-render/src/node/element/textarea.js, packages/miniapp-render/src/node/element/video.js, packages/miniapp-render/src/node/root.js, packages/miniapp-render/src/node/style.js, packages/miniapp-render/src/node/text-node.js, packages/miniapp-render/src/utils/tool.js, packages/miniapp-render/src/utils/tree.js
=> refactor(miniapp): simplify-setData

packages/jsx2mp-loader/src/component-loader.js
move eliminateDeadCode to try-catch
=> fix:move-eliminateDeadCode-try-catch

packages/rax-miniapp-runtime-webpack-plugin/src/index.js, packages/rax-miniapp-runtime-webpack-plugin/src/utils/addFileToCompilation.js, packages/rax-miniapp-runtime-webpack-plugin/src/utils/minifyCode.js, packages/rax-miniapp-runtime-webpack-plugin/src/utils/wrapChunks.js
=> feat(miniapp): minify css files

packages/miniapp-render/src/node/element.js, packages/miniapp-render/src/node/element/image.js, packages/miniapp-render/src/node/element/input.js, packages/miniapp-render/src/node/element/textarea.js, packages/miniapp-render/src/node/element/video.js, packages/miniapp-render/src/utils/tool.js
=> refactor(miniapp): normalize classNames

packages/driver-miniapp/README.md, packages/driver-miniapp/package.json, packages/driver-miniapp/src/index.ts, packages/driver-miniapp/tsconfig.json, tsconfig.json
=> chore(miniapp): simplify driver-miniapp code

packages/miniapp-render/src/builtInComponents/ad.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/baidu.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/bytedance.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/kuaishou.js, packages/rax-miniapp-runtime-webpack-plugin/src/platforms/wechat.js
=> feat(miniapp): support ad component

packages/jsx2mp-runtime/package.json, packages/jsx2mp-runtime/src/component.js, packages/jsx2mp-runtime/src/hooks.js
=> fix(jsx2mp): shouldUpdate logic and useReducer not work

packages/jsx2mp-loader/src/output.js
=> fix(jsx2mp): can't process ts optional chain

packages/jsx2mp-runtime/.babelrc, packages/jsx2mp-runtime/package.json, packages/jsx2mp-runtime/src/__tests__/arrayDiff.js, packages/jsx2mp-runtime/src/__tests__/createStyle.js, packages/jsx2mp-runtime/src/__tests__/propsDiff.js, packages/jsx2mp-runtime/src/component.js, packages/jsx2mp-runtime/src/diff.js
对比本次data与上次data之间的diff，找出最小变更路径。通过小程序setData 路径更新能力实现数据更新，减少每次setData传输的数据量
=> feat:新增diff data,优化小程序setData性能

packages/miniapp-compile-config/package.json
remove unused dependency `@builder/pack`
=> chore: drop unused dep `@builder/pack`

packages/rax-miniapp-runtime-webpack-plugin/CHANGELOG.md, packages/rax-miniapp-runtime-webpack-plugin/package.json, packages/rax-miniapp-runtime-webpack-plugin/src/generators/app.js
https://github.com/raxjs/miniapp/pull/299
=> fix: css sourcemap will be handled as css files

packages/jsx2mp-loader/CHANGELOG.md, packages/jsx2mp-loader/package.json
Update CHANGELOG and version for release.
=> doc(jsx2mp-loader): changelog and version

packages/rax-miniapp-runtime-webpack-plugin/src/platforms/wechat.js
=> feat: support onChooseAvatar
