raxjs/miniapp

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/code.js
- packages/jsx2mp-runtime/package.json
- packages/jsx2mp-runtime/src/updater.js
> Release/jsx2mp 0.4.15

- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/script-loader.js
> feat(jsx2mp): omit ts file when copying

- packages/miniapp-render/package.json
- packages/miniapp-render/src/utils/getProperty.js
> fix(miniapp-render): render data computed incorrectly in wechat

- packages/rax-miniapp-babel-plugins/src/plugins/babel-plugin-handle-native-component.js
- packages/rax-miniapp-babel-plugins/src/utils/handleComponentAST.js
fix bug of runtime mode
```js
// a/lib/miniapp/index
import { a, b } from 'a';
import A, { a, b } from 'a';
// =>
// keep import after compile
import { a, b } from 'a';
```
> fix: runtime-import-multi-specifier-of-native-component

- packages/miniapp-render/package.json
- packages/miniapp-render/src/node/element.js
- packages/miniapp-render/src/utils/getProperty.js
- packages/rax-miniapp-babel-plugins/package.json
- packages/rax-miniapp-babel-plugins/src/plugins/babel-plugin-handle-native-component.js
- packages/rax-miniapp-babel-plugins/src/utils/handleComponentAST.js
- packages/rax-miniapp-runtime-webpack-plugin/package.json
- packages/rax-miniapp-runtime-webpack-plugin/src/generators/app.js
- packages/rax-miniapp-runtime-webpack-plugin/src/templates/rax-default.css.ejs
> Release/miniapp 1.2.6

- packages/miniapp-render/package.json
- packages/miniapp-render/src/builtInComponents/map.js
- packages/rax-miniapp-runtime-webpack-plugin/package.json
- packages/rax-miniapp-runtime-webpack-plugin/src/templates/wechat-miniprogram/root.xml.ejs
> fix(miniapp): scroll-into-view doesn't work in wechat and map onRegionChange error in ali miniapp

- packages/rax-miniapp-babel-plugins/src/utils/handleComponentAST.js
code
```js
import NativeComponent from 'native-component';
export default function App() {
return (
<View>
<NativeComponent />
<NativeComponent />
<View>
)
}
```
expect
```html
<view>
<native-component />
<native-component />
</view>
```
actual
```html
<view>
<native-component />
<view class="h5-native-component" />
</view>
```
> fix: runtime mode multi native component render error

- packages/jsx2mp-runtime/src/createRef.js
Add RefFn function prototype to fix "n.apply is not a function" in Ali mini app
> fix: createRef's function methods missing

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/modules/components.js
- packages/jsx-compiler/src/utils/pathHelper.js
- packages/jsx2mp-runtime/package.json
> Release/jsx2mp 0.4.17

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/__tests__/style.js
- packages/jsx-compiler/src/modules/css.js
- packages/jsx-compiler/src/modules/style.js
- packages/jsx-compiler/src/utils/pathHelper.js
支持在小程序编译时中使用 CSS Modules 的写法 (但不混淆 class 类名)
Input:
```js
import styles from './index.module.css';
// ...
<View className={styles.home} />
```
Output: 
```axml
<view class="home" />
```
> feat(jsx2mp): support css modules (without className mixup)

- packages/rax-miniapp-runtime-webpack-plugin/src/generators/app.js
- packages/rax-miniapp-runtime-webpack-plugin/src/utils/adjustCSS.js
- packages/rax-miniapp-runtime-webpack-plugin/src/utils/wrapChunks.js
```css
:root {}   
```
to
```
page { }
```
> fix: :root selector is not supported in wechat miniprogram

- packages/jsx-compiler/src/modules/__tests__/element.js
- packages/jsx-compiler/src/modules/__tests__/render-function.js
- packages/jsx-compiler/src/modules/__tests__/render-props.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx-compiler/src/utils/getDefaultComponentFunctionPath.js
从 props 或 this.props 中解构出的变量也能识别到，然后不将其转换为绑定变量，以通过原生 props 更新机制更新子组件
Input: 
```js
const { name } = props;
return (<View>{name}</View>)
```
Before:
```xml
<view>{{_d0}}</view>
```
After:
```xml
<view>{{name}}</view>
```
> feat(jsx2mp): support idenfy variable derived from props

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/code.js
- packages/jsx-compiler/src/utils/getAliasCorrespondingValue.js
> fix(jsx2mp): can't get correct npm path

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/__tests__/element.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx-compiler/src/modules/render-props.js
- packages/jsx-compiler/src/utils/isDerivedFromProps.js
```js
const { family } = props;
const { name } = family;
```
> fix(jsx2mp): variables with default assignment should be transformed

- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/script-loader.js
> fix(jsx2mp): use loader content as input instead of rawContent

- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/code.js
> fix(jsx2mp): exclude app json file import

- packages/jsx-compiler/src/codegen/genCode.js
- packages/jsx-compiler/src/codegen/genExpression.js
- packages/jsx-compiler/src/modules/__tests__/element.js
- packages/jsx-compiler/src/modules/css.js
- packages/jsx-compiler/src/modules/element.js
- packages/jsx-compiler/src/utils/isDerivedFromProps.js
如以下示例：
```js
const { person: { name, age = 20}, school, grade = 9 } = props;
```
其中只有 school 可以保留，其他变量均需要转换为 data
```js
// app.js
// 以下两句代码在产物中应当被删除
import './app.less';
import styles from './default.module.css';
```
> fix(jsx2mp): jsx-compiler bug

- packages/rax-miniapp-runtime-webpack-plugin/src/platforms/wechat.js
> fix(miniapp): add animation in view and refactor map children

- packages/miniapp-render/CHANGELOG.md
- packages/miniapp-render/src/createConfig/app.js
- packages/rax-miniapp-runtime-webpack-plugin/CHANGELOG.md
- packages/rax-miniapp-runtime-webpack-plugin/src/utils/wrapChunks.js
分包抽取 `vendor` 的情况下，每个 JS Bundle 外层包裹的 document 需要在页面切换的时候更新：
```js
module.exports = function(window, document) {
// 业务 bundle
}
```
> fix: miniapp vendor document toggle

- packages/miniapp-render/src/constants.js
- packages/miniapp-render/src/node/element.js
- packages/rax-miniapp-runtime-webpack-plugin/src/platforms/wechat.js
针对微信小程序端 scroll-view 中 scroll-top 和 scroll-left 可能影响 scroll-into-view 的问题，给出定制化的 scroll-view。用户在 rax-scrollview 或 scroll-view 上配置 anchorScroll 时即可启用无 scroll-top 和 scroll-left 的 scroll-view 模板
> feat: support custom scrollview

- packages/rax-miniapp-runtime-webpack-plugin/src/platforms/wechat.js
> fix(miniapp): miss marker-id and slot in cover-view

- packages/miniapp-render/src/bridge/createEventProxy.js
> fix(miniapp): get target from event.currentTarget

- packages/rax-miniapp-runtime-webpack-plugin/src/generators/templates/baseTemplate.js
feat: 运行时小程序支持用户在 `build.json` 中对某组件增加默认属性配置，示例方式如下：
```json
"miniapp": {
"template": {
"cover-view": {
"add": {
"props": [
{
"name": "test1",
"default": "232"
},
{
"name": "test2",
"default": 233
},
{
"name": "test3",
"default": false
}
]
}
}
}
}
```
> feat(miniapp): support add props for component template

- packages/jsx-compiler/CHANGELOG.md
- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/code.js
- packages/jsx2mp-loader/CHANGELOG.md
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/script-loader.js
> feat(jsx2mp): make exports compatible

- packages/jsx-compiler/CHANGELOG.md
- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/code.js
- packages/jsx2mp-loader/CHANGELOG.md
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/script-loader.js
> fix(jsx2mp): miss basedir config in resolve function

- packages/miniapp-runtime-config/CHANGELOG.md
- packages/miniapp-runtime-config/package.json
- packages/miniapp-runtime-config/src/setConfig.js
> feat(miniapp): remove copy-webpack-plugin dependency

- packages/miniapp-render/src/constants.js
- packages/miniapp-render/src/createConfig/app.js
- packages/miniapp-render/src/createConfig/page.js
- packages/miniapp-render/src/document.js
- packages/miniapp-render/src/node/attribute.js
- packages/miniapp-render/src/utils/cache.js
- packages/rax-miniapp-runtime-webpack-plugin/src/generators/app.js
- packages/rax-miniapp-runtime-webpack-plugin/src/utils/wrapChunks.js
> feat(miniapp): move js bundle execution time to app onLaunch in wechat

- packages/miniapp-render/src/bridge/createEventProxy.js
- packages/miniapp-render/src/event/event-target.js
- packages/miniapp-runtime-config/src/setConfig.js
Rax 小程序经过模板优化后，未绑定点击事件的组件，其模板上将不再绑定 onTap 事件，其导致用户在以下情况下，获取的 e.target 为根节点：
```jsx
export default function Home() {
useEffect(() => {
document.addEventListener('click', function(e) {
debugger;
console.log('e', e.target);
}, true);
}, []);
return (
<View>
<Text id="test1">未绑定点击事件</Text>
<Text id="test2" onClick={() => {console.log(123123)}}>已绑定点击事件</Text>
</View>
);
}
```
原因在于，用户点击 test2 节点时，该节点对应模板上绑定的 onTap 事件触发，其经过 rax 小程序内部的事件系统处理冒泡捕获等流程。而用户点击 test1 节点时，模板上未绑定 onTap，只有根节点对应模板的 onTap 事件触发，导致用户获取的 target 错误指向根节点。因此代码修改为生成 event 对象时，优先以小程序原生返回的 target 为准，并且回滚之前的从 event.target 获取 dataset 的操作。
> fix(miniapp): can't get correct event target

- packages/miniapp-render/__tests__/event/event.test.js
- packages/miniapp-render/src/event/event-target.js
> fix(miniapp): can't return correct event target

- packages/miniapp-builder-shared/src/autoInstallNpm.js
- packages/miniapp-compile-config/src/plugins/AutoInstallNpm.js
- packages/rax-miniapp-runtime-webpack-plugin/src/generators/pkg.js
- packages/rax-miniapp-runtime-webpack-plugin/src/index.js
微信小程序支持在分包目录下安装 npm 包以减轻主包体积压力。Rax 小程序需要用户在 `build.json` 的 `nativePackage` 中增加以下配置，以支持上述能力：
```json
{
"targets": [
"wechat-miniprogram"
],
"wechat-miniprogram": {
"subPackages": true,
"nativePackage": {
"autoInstall": false,
// 主包安装依赖
"dependencies": {
"jquery": "*",
"axios": "*"
},
// 其他子包安装依赖
"subPackages": [
{
// source 对应子包入口 app 代码
"source": "pages/About/app",
"dependencies": {
"jquery": "*"
}
},
{
"source": "pages/Profile/app",
"dependencies": {
"lodash": "*"
}
}
]
}
},
}
```
> feat(miniapp): support install npm in subpackages

- packages/jsx-compiler/CHANGELOG.md
- packages/jsx-compiler/package.json
- packages/jsx-compiler/src/modules/__tests__/jsx-plus.js
- packages/jsx-compiler/src/modules/__tests__/list.js
- packages/jsx-compiler/src/modules/jsx-plus.js
- packages/jsx-compiler/src/modules/list.js
> fix: return renamed index in list

- packages/rax-miniapp-runtime-webpack-plugin/src/generators/templates/baseTemplate.js
```json
"miniapp": {
"template": {
"delete": ["canvas", "progress"]
}
}
```
> feat(miniapp): support delete useless components

- packages/miniapp-render/CHANGELOG.md
- packages/miniapp-render/package.json
- packages/miniapp-render/src/node/element.js
修复：当新老节点都为注释节点时，忽略在 replaceChild 函数中更新；
问题：当使用 Fragment 时，无论内容是否发生变化，都会触发更新
修改前：
修改后：
> fix: avoid the update in 'replaceChild'  if both nodes are Comment node

- packages/miniapp-render/src/builtInComponents/canvas.js
- packages/rax-miniapp-runtime-webpack-plugin/src/platforms/ali.js
> fix(miniapp): onCanvasReady can't emit

- packages/jsx2mp-runtime/CHANGELOG.md
- packages/jsx2mp-runtime/package.json
- packages/jsx2mp-runtime/src/component.js
- packages/jsx2mp-runtime/src/nativeEventListener.js
修改前：`addNativeEventListener` 中注册的事件被绑定在页面组件上，导致同一个页面组件实例出来的不同页面会共享事件。
修改后：`addNativeEventListener` 中注册的事件被绑定在页面实例上，解决共享事件的问题。
> Fix: Bind native events on page instance other than page component

- packages/jsx2mp-loader/CHANGELOG.md
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/component-loader.js
- packages/jsx2mp-loader/src/page-loader.js
> fix(jsx2mp): can't find correct app_css usingComponents path

- packages/jsx2mp-loader/src/styleProcessor.js
问题：现在的rem 替换为 rpx 采用的直接字符串替换；这样会误伤 css 类名中的 rem，如上图。
修复：只替换 css 属性值内的 rem，且特征符合 css 单位的有效语法。
注： converCSSUnit 的参数如果走默认值，其他使用该函数的地方也会有此问题（虽然搜索整个仓库只有一处调用），所以去掉了默认值，加了检查。 调用处明确传参进来。
> fix:just replace 'rem' in css value of specific pattern, to prevent break css name or css key

- packages/jsx2mp-loader/CHANGELOG.md
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/script-loader.js
纯api类型的组件模块通过文件后缀名（index.ali.js | index.wechat.js | ... ）做分端构建时，虽然他端文件剔除了，但是文件名称和被引用路径不一致，会导致运行出错（如：产物模块 util/index.ali.js 与被引用 import Util from '../apis/util/index'）。故纯API模块分端构建后的产物文件名改为index.js来修复这个问题。
> fix(jsx2mp-loader): component of pure js support shaking by filename postfix

- packages/jsx2mp-loader/CHANGELOG.md
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/styleProcessor.js
修复之前的写法存在两个问题：
1. \s* 的写法有问题，实际匹配的是多个 's'，未达到匹配多个空白符的目的；
2. 基于第一个问题，会出现 new RegExp('.+rem', 'g')，匹配特长的字符串时，会因为回溯过多导致卡死；（千郎那个问题正是在含有较长base64时触发的）
> fix: convertCSSUnit rem 2 rpx

- packages/jsx2mp-loader/CHANGELOG.md
- packages/jsx2mp-loader/package.json
- packages/jsx2mp-loader/src/utils/pathHelper.js
修复 removeExt 的正则错误，之前的写法在开启纯 api 文件的分端构建后（[pr#278](https://github.com/raxjs/miniapp/pull/278)），会误伤 dir/ali.js, dir/wechat.js 这种格式的文件，导致其构建产物变为 dir.js。
之前的正则表达式字面量写法的 /\\\\./ 有问题，’.‘ 的转义最终没有生效。简单测试如图：
故修复让其只对 dir/xx.ali.js, dir/xx.wechat.js 这样的文件名生效 分端构建。
----
目前通过 env 判断来动态 require 对应端文件是常见的纯 api 文件实现 “分端构建” 的方式，而这种方式下对文件的命名，开发者的习惯都是以 ali.js wechat.js 来命名的。如下图：
> fix: RegExp of function removeExt

- packages/miniapp-compile-config/src/setEntry.js
如沟通。编译时方案下，“引用原生小程序页面”功能，将原生页面放在 `pages/` 目录下时，拷贝后的路径有误，被放到 `build/miniapp/src/pages/` 下了，正确应该是 `build/miniapp/pages/` 下。 这里修复一下这个 `to`  的路径。
> fix: needCopyList[i].to error in setEntry()

- packages/rax-miniapp-runtime-webpack-plugin/src/utils/processAssets.js
避免开启sourcemap 之后的。xxx.css.map 文件被处理导致格式异常报错
> fix:css file test

- packages/jsx-compiler/src/adapter.js
- packages/jsx-compiler/src/modules/components.js
如图，字节小程序IDE 上遇到以下划线开头的自定义组件命名，不识别（语法不高亮），渲染异常。
命名去掉开头下划线后，渲染正常，如下图：
故在字节小程序上的自定义组件命名开头是 ’@' 时，做特殊处理，来规避此问题。
Npm分组都是 '@xxx/' 开头的格式，转为 ‘xxx_' 格式，不会出现碰撞。
> fix(bytedance): componentTag don't sopport the name start with '_'
